//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BU
{
    using System;
    using System.Collections.Generic;
    
    public partial class stageplaatsen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public stageplaatsen()
        {
            this.aantal = 0;
        }
    
        public Nullable<int> aantal { get; set; }
        public string bedrijf { get; set; }
    }
}
